[parity]
chain = "/thaichain/spec.json"
base_path = "/thaichain/data"

[network]
port = 30333
min_peers = 25
max_peers = 50
nat = "any"
id = 7
bootnodes = [
   "enode://283b26316aba0b0c3bd5eb3c73e5a3aa0b24af9c09bc74c07cede2ac80d4354fee1fbe6dd3b448b077bb0b9a0b19dbc03ee0e5fa5032c368a41460da2dd36d40@thaichain.kku.ac.th:30333"
]


[rpc]
interface = "all"
cors = ["all"]
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]


[websockets]
port = 8546
interface = "all"

