[parity]
chain = "/thaichain/spec.json"
base_path = "/thaichain/data"

[network]
port = 30333
min_peers = 25
max_peers = 50
nat = "any"
id = 7

[rpc]
interface = "all"
cors = ["all"]
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]


[websockets]
port = 8546
interface = "all"

