[parity]
chain = "/thaichain/spec.json"
base_path = "/thaichain/data"

[network]
port = 30333
min_peers = 25
max_peers = 50
id = 7
discovery=true
reserved_only = false
reserved_peers = "/thaichain/peers.txt"

[rpc]
disable = true

[account]
unlock = []
password = ["/thaichain/data/password.txt"]

[mining]
engine_signer = "0x0184555297adc495cdfc391d819ab955fa4284ab"
reseal_on_txs = "none"

[websockets]
disable = true

