[parity]
chain = "/thaichain/spec.json"
base_path = "/thaichain/data"

[network]
port = 30333
min_peers = 25
max_peers = 50
nat = "any"
id = 7

[rpc]
disable = true

[account]
unlock = []
password = ["/thaichain/data/password.txt"]

[mining]
engine_signer = "0x0184555297adc495cdfc391d819ab955fa4284ab"
reseal_on_txs = "none"

[websockets]
disable = true

